export const DEFAULT_COLUMN_WIDTH = 140
export const DEFAULT_MIN_COLUMN_WIDTH = 100
export const DEFAULT_HEADER_ROW_HEIGHT = 30
export const DEFAULT_ROW_MARKER_WIDTH = 44
export const DEFAULT_SCROLLBAR_RESERVE = 12

export const COLUMN_HIGHLIGHT_COLOR = '#1e88e5'

