import type { DataRow, NetworkNode } from './types'
import type { BasicGridSelectOption } from '../components/BasicGrid'

export type { DataRow, NetworkNode }

const DEFAULT_STATUS_OPTIONS = ['Активен', 'На обучении', 'В отпуске', 'На испытательном сроке']

export const createStatusOptions = (options: string[] = DEFAULT_STATUS_OPTIONS): BasicGridSelectOption[] =>
  options.map((label) => ({ label, value: label }))

export const createStatus = (name: string, options: string[] = DEFAULT_STATUS_OPTIONS) => ({
  name,
  options: createStatusOptions(options),
})

export const basicGridRows: DataRow[] = [
  {
    employeeId: 'EMP-001',
    firstName: 'Анна',
    lastName: 'Иванова',
    name: 'Анна Иванова',
    age: 29,
    role: 'Product Manager',
    department: 'Разработка',
    salary: 185000,
    city: 'Москва',
    email: 'anna.ivanova@example.com',
    contact: {
      email: 'anna.ivanova@example.com',
      phone: '+7 (495) 100-20-30',
    },
    address: {
      street1: 'ул. Тверская, 5',
      city: 'Москва',
      state: 'Москва',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 82,
    actions: '',
  },
  {
    employeeId: 'EMP-002',
    firstName: 'Михаил',
    lastName: 'Петров',
    name: 'Михаил Петров',
    age: 34,
    role: 'Backend Engineer',
    department: 'Разработка',
    salary: 210000,
    city: 'Санкт-Петербург',
    email: 'mikhail.petrov@example.com',
    contact: {
      email: 'mikhail.petrov@example.com',
      phone: '+7 (812) 340-10-22',
    },
    address: {
      street1: 'Наб. реки Фонтанки, 44',
      city: 'Санкт-Петербург',
      state: 'Ленинградская область',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 68,
    actions: '',
  },
  {
    employeeId: 'EMP-003',
    firstName: 'Екатерина',
    lastName: 'Смирнова',
    name: 'Екатерина Смирнова',
    age: 31,
    role: 'UX Lead',
    department: 'Дизайн',
    salary: 165000,
    city: 'Казань',
    email: 'ekaterina.smirnova@example.com',
    contact: {
      email: 'ekaterina.smirnova@example.com',
      phone: '+7 (843) 555-33-77',
    },
    address: {
      street1: 'ул. Баумана, 12',
      city: 'Казань',
      state: 'Татарстан',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 74,
    actions: '',
  },
  {
    employeeId: 'EMP-004',
    firstName: 'Дмитрий',
    lastName: 'Волков',
    name: 'Дмитрий Волков',
    age: 28,
    role: 'Data Analyst',
    department: 'Аналитика',
    salary: 152000,
    city: 'Новосибирск',
    email: 'dmitry.volkov@example.com',
    contact: {
      email: 'dmitry.volkov@example.com',
      phone: '+7 (383) 111-45-67',
    },
    address: {
      street1: 'Красный проспект, 98',
      city: 'Новосибирск',
      state: 'Новосибирская область',
      country: 'Россия',
    },
    status: createStatus('На обучении'),
    progress: 59,
    actions: '',
  },
  {
    employeeId: 'EMP-005',
    firstName: 'Ирина',
    lastName: 'Кузнецова',
    name: 'Ирина Кузнецова',
    age: 33,
    role: 'HR Business Partner',
    department: 'HR',
    salary: 138000,
    city: 'Екатеринбург',
    email: 'irina.kuznetsova@example.com',
    contact: {
      email: 'irina.kuznetsova@example.com',
      phone: '+7 (343) 240-08-55',
    },
    address: {
      street1: 'пр. Ленина, 24',
      city: 'Екатеринбург',
      state: 'Свердловская область',
      country: 'Россия',
    },
    status: createStatus('В отпуске'),
    progress: 35,
    actions: '',
  },
  {
    employeeId: 'EMP-006',
    firstName: 'Павел',
    lastName: 'Соколов',
    name: 'Павел Соколов',
    age: 38,
    role: 'Sales Director',
    department: 'Продажи',
    salary: 198000,
    city: 'Нижний Новгород',
    email: 'pavel.sokolov@example.com',
    contact: {
      email: 'pavel.sokolov@example.com',
      phone: '+7 (831) 905-44-11',
    },
    address: {
      street1: 'ул. Большая Покровская, 8',
      city: 'Нижний Новгород',
      state: 'Нижегородская область',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 91,
    actions: '',
  },
  {
    employeeId: 'EMP-007',
    firstName: 'Светлана',
    lastName: 'Миронова',
    name: 'Светлана Миронова',
    age: 27,
    role: 'Marketing Lead',
    department: 'Маркетинг',
    salary: 167000,
    city: 'Самара',
    email: 'svetlana.mironova@example.com',
    contact: {
      email: 'svetlana.mironova@example.com',
      phone: '+7 (846) 400-70-10',
    },
    address: {
      street1: 'ул. Ленинградская, 18',
      city: 'Самара',
      state: 'Самарская область',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 64,
    actions: '',
  },
  {
    employeeId: 'EMP-008',
    firstName: 'Олег',
    lastName: 'Баранов',
    name: 'Олег Баранов',
    age: 35,
    role: 'DevOps Engineer',
    department: 'Инфраструктура',
    salary: 175000,
    city: 'Краснодар',
    email: 'oleg.baranov@example.com',
    contact: {
      email: 'oleg.baranov@example.com',
      phone: '+7 (861) 310-55-66',
    },
    address: {
      street1: 'ул. Красная, 45',
      city: 'Краснодар',
      state: 'Краснодарский край',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 77,
    actions: '',
  },
  {
    employeeId: 'EMP-009',
    firstName: 'Виктор',
    lastName: 'Громов',
    name: 'Виктор Громов',
    age: 42,
    role: 'QA Lead',
    department: 'Тестирование',
    salary: 142000,
    city: 'Воронеж',
    email: 'victor.gromov@example.com',
    contact: {
      email: 'victor.gromov@example.com',
      phone: '+7 (473) 700-55-21',
    },
    address: {
      street1: 'ул. Плехановская, 15',
      city: 'Воронеж',
      state: 'Воронежская область',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 71,
    actions: '',
  },
  {
    employeeId: 'EMP-010',
    firstName: 'Татьяна',
    lastName: 'Галкина',
    name: 'Татьяна Галкина',
    age: 30,
    role: 'Product Analyst',
    department: 'Аналитика',
    salary: 158000,
    city: 'Пермь',
    email: 'tatyana.galkina@example.com',
    contact: {
      email: 'tatyana.galkina@example.com',
      phone: '+7 (342) 320-47-88',
    },
    address: {
      street1: 'ул. Ленина, 60',
      city: 'Пермь',
      state: 'Пермский край',
      country: 'Россия',
    },
    status: createStatus('Активен'),
    progress: 66,
    actions: '',
  },
]

export const networkData: NetworkNode[] = [
  {
    id: '3190',
    name: 'ЦОД · Москва',
    type: 'region',
    status: 'Онлайн',
    load: 82,
    latency: 18,
    items: [
      {
        id: '31469',
        name: 'Кластер API',
        type: 'cluster',
        status: 'Онлайн',
        load: 74,
        latency: 12,
        items: [],
      },
      {
        id: '31470',
        name: 'Маршрутизатор ядра',
        type: 'router',
        status: 'Деградация',
        load: 91,
        latency: 22,
        items: [
          {
            id: '3144141',
            name: 'Транк M9 · линия 1',
            type: 'link',
            status: 'Онлайн',
            load: 55,
            latency: 6,
            items: [],
          },
          {
            id: '3144142',
            name: 'Транк M9 · линия 2',
            type: 'link',
            status: 'Онлайн',
            load: 61,
            latency: 7,
            items: [],
          },
          {
            id: '3144143',
            name: 'Edge CDN #01',
            type: 'edge',
            status: 'Перегрев',
            load: 96,
            latency: 15,
            items: [],
          },
          {
            id: '3144144',
            name: 'Edge CDN #02',
            type: 'edge',
            status: 'Онлайн',
            load: 72,
            latency: 11,
            items: [],
          },
        ],
      },
      {
        id: '31471',
        name: 'Кластер хранения',
        type: 'storage',
        status: 'Онлайн',
        load: 64,
        latency: 9,
        items: [],
      },
    ],
  },
  {
    id: '3191',
    name: 'Регион · Санкт-Петербург',
    type: 'region',
    status: 'Онлайн',
    load: 58,
    latency: 25,
    items: [
      {
        id: '31480',
        name: 'Edge шлюз · Нева',
        type: 'edge',
        status: 'Онлайн',
        load: 47,
        latency: 13,
        items: [],
      },
    ],
  },
]

